# Generated by Django 5.1.4 on 2024-12-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Smaerphone'), ('ML', 'Laptop'), ('LS', 'Tablet'), ('MS', 'Gadget'), ('PN', 'Accessories'), ('GH', 'Console')], max_length=2),
        ),
    ]
